### ISSUE TITLE
HEP-GO

### ISSUE THREAD

**Issue by lmangani** [negbie/horaclifix#1]
Not sure you saw it, but there's already a HEP-GO you can plug and wire here: https://github.com/sipcapture/hep-go/blob/master/hep.go

**Comment by negbie** [comment]
Hi Lorenzo,

thank you, i saw that some time ago but forgot it. Damit, that would have 
saved me almost 2 hours yesterday ;) I will have a look at it.

BR,
Eugen


Am 21. Juni 2017 8:14:37 vorm. schrieb Lorenzo Mangani 
<notifications@github.com>:

**Comment by negbie** [comment]
OK now i now why i forgot it :) its a Decoder not a Encoder. But at least i 
can take the fieldnames. Thank you anyway!


Am 21. Juni 2017 8:14:37 vorm. schrieb Lorenzo Mangani 
<notifications@github.com>:

**Comment by lmangani** [comment]
well, once you have the structure its just an UDP message so I hope it still saves you some minutes :)

**Comment by negbie** [comment]
yeah thats true but for learning purposes i decided to write my own 
implementation ;)


Am 21. Juni 2017 10:48:39 vorm. schrieb Lorenzo Mangani 
<notifications@github.com>:
