### ISSUE TITLE
Many warnings when using horaclifix 1.1.3 with heplify-server 0.96

### ISSUE THREAD

**Issue by MosinAnton** [negbie/horaclifix#10]
2018-10-09T16:32:21+05:00 WARN HEP chunkType 3 should be 4 byte long but is 16
2018-10-09T16:32:21+05:00 WARN HEP chunkType 3 should be 4 byte long but is 16
2018-10-09T16:32:21+05:00 WARN HEP chunkType 3 should be 4 byte long but is 16

with 1.1.2 everything ok

**Comment by negbie** [comment]
Hi right now I'm at astricon so it will take some days to look at it. In the mean time just use the -protobuf flag and you should be good to go. Keep in mind this flag could be removed in future releases.

**Comment by MosinAnton** [comment]
With -protobuf works. Thank you!

**Comment by negbie** [comment]
Your welcome. Please let this issue open so I can look at it when I'm back home.

**Comment by negbie** [comment]
@MosinAnton should be fixed in 1.1.4. Please test and report back. Thanks for pointing me at this issue!
