### ISSUE TITLE
Missing Source & Destination info in Homer

### ISSUE THREAD

**Issue by DavidR000** [negbie/horaclifix#11]
Hi,

I have been trying to use horaclifix to push information from my ACME's into homer.  Works great but  in Homer the source and destination IP addresses are now showing as 0.0.0.0 (they populate if i use hepfix but that keeps crashing) .

Is there anything i can do to get those populated form horaclifix?

horaclifix 1.1.3
ACME SCZ740m2_Acme_3820

Thanks

Dave

**Comment by negbie** [comment]
Hi @DavidR000 ,

it seems that I have introduced a bug with the latest release. See here

https://github.com/negbie/horaclifix/issues/10

Could you tell me please if you have IPv4 traffic only and which capture server you are using?

**Comment by DavidR000** [comment]
Hi, Thanks for the prompt reply,
Yes, we are only processing IPV4 traffic at present  and we are using Homer with opensip

**Comment by negbie** [comment]
Hi,
ok thanks for the info. I've ask about the capture sever because with heplify-server there would be a workaround. Ok so let me fix this over the day and I will publish a new release soon.

**Comment by negbie** [comment]
@DavidR000 just want to let you know that while I'm working on the fix you can also use 1.1.2. It's the same like 1.1.3 but has no IPv6 support.

**Comment by negbie** [comment]
@DavidR000 should be fixed in 1.1.4. Please test and report back.

**Comment by DavidR000** [comment]
Loaded that this morning and 1.1.4  seems to be working perfectly now, Thank you!

**Comment by negbie** [comment]
Ok thanks for the info. Closing
