### ISSUE TITLE
verbose flag

### ISSUE THREAD

**Issue by lmangani** [negbie/horaclifix#3]
The -v option from the example does not seem to be accepted: 
```
flag provided but not defined: -v
```

**Comment by negbie** [comment]
Hi Lorenzo. Mby you have a older version? Could you provide the ./horaclifix -h output?

**Comment by negbie** [comment]
This should be the output of the latest version:
./horaclifix -h

Usage of ./horaclifix:
  -H string
        Homer server address
  -P string
        HEP capture password (default "myhep")
  -d    Debug output to stdout
  -g string
        Graylog server address
  -l string
        IPFIX listen address (default ":4739")
  -n string
        SBC name in graylog (default "sbc")
  -s string
        StatsD server address
  -v    Verbose output to stdout

**Comment by lmangani** [comment]
right... that was it :) apparently GO get/install do not fetch updates... is there a command to do that? Right now forcing a remove/install on each startup of the Horaclifix docker container

**Comment by negbie** [comment]
go get -u github.com/negbie/horaclifix

**Comment by negbie** [comment]
Just one hint if you test versions >= 0.5 with hammerhep. I handle errors more strictly now. That means if horaclifix get's some weired packets it waits for the next handshake. So we can guarantee that we are in sync.

**Comment by lmangani** [comment]
FYI: https://github.com/lmangani/horaclifix-go-docker
