### ISSUE TITLE
Uraclifix + heplify-server howto

### ISSUE THREAD

**Issue by dvillaume** [negbie/horaclifix#8]
Hi again, 

Here are some questions i dind't answered on my own.

what kind of metrics/logs could be obtain ?

what should be the config of dockers to work together with prometheus without double logging (docker_hom5-hep-prom-graf + horaclifix-docker ) ?

Is there any generic dashbord i should add to web-app to enjoy all features

Thx

**Comment by negbie** [comment]
As far as I know you use heplify-server right? While horaclifix can expose prometheus metrics by its own too its not needed to activate them when you use heplify-server. Horaclifix sends hep encapsulated SIP messages and RTP+RTCP stats as json to heplify-server which will expose them as prometheus metrics. When you use the docker_hom5-hep-prom-graf docker compose file it will bring up grafana will a lot of usefull sample dashboards.

**Comment by dvillaume** [comment]
Thanks for this answer, dashboards are fantastics as soon as promotheus IP has been defined.
