### ISSUE TITLE
Displaying Call Flow

### ISSUE THREAD

**Issue by sve71** [negbie/horaclifix#9]
Hi,

I’ve already created the issue [here](https://github.com/sipcapture/homer/issues/311). My question was why sometimes I see in call flow that 100 Trying goes before INVITE? And the answer was it’s because my capture agent uses < HEP3 mby. Could you tell what the version of HEP is used by horaclifix ? The thing is I can’t use any other agents because the only way to get SIP from our SBCs is using comm-monitor… So is it possible that my issue is in horaclifix?

BR,
Sergey

**Comment by negbie** [comment]
Hi,
has this sbc AND the capture server a propper NTP setup? This is very important! When you use heplify-server as capture server could you run it in debug mode an search the logs for
"packet with timestamp in the future"

**Comment by negbie** [comment]
horaclifix sends HEP3

**Comment by sve71** [comment]
How I can run heplify-server in debug mode? Unfortunatelly I didn't find the necessary key in the
`./heplify-server -h`
listing...
Or you are talking about the keys:
```
-logdbg
      Change value of LogDbg.
-loglvl
      Change value of LogLvl. (default info)
-logstd
      Change value of LogStd.

```
And nevertheless I'll check a configuration of the SBCs.

**Comment by negbie** [comment]
Let me explain these flags.
-logdbg hep,sql
can take some predefined selectors and give you more infos about hep packets and sql. Its basicly a debug mode for certain selectors

-loglvl debug
will activate the classic debug mode and give you debug messages from all selectors

-logstd
will print the messages on console

So what you want is
-loglvl debug

But first check your NTP setup on the host where heplify-server is running AND the sbc.
